pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(-preview)?\[bot\]$
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
      - status-success=coverage/coveralls
    actions:
      merge:
        method: merge
      delete_head_branch: {}
